image: python:3.8

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - requirements.txt
      - dist/

test:
  stage: test
  script:
    - pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
  only:
    - master
